development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "Uo84JGW88jEWyqPaVvPkR54uRs4iiOsy@redis-10981.c258.us-east-1-4.ec2.cloud.redislabs.com:10981" } %>
  channel_prefix: final_project_production
