development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://:p2e9e90a8ff52e959460e4c3032a50ae95ea07136ea07aab0eca5d6ca31fc6aca@ec2-44-208-126-108.compute-1.amazonaws.com:7189" } %>
  channel_prefix: woofie_app_production
