default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: final-project_development

test:
  <<: *default
  database: final-project_test

production:
  <<: *default
  database: final-project_production
  username: final-project
  password: <%= ENV["FINAL-PROJECT_DATABASE_PASSWORD"] %>