default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: woofie-app_development

test:
  <<: *default
  database: woofie-app_test

production:
  <<: *default
  database: woofie-app_production
  username: woofie-app
  password: <%= ENV["WOOFIE-APP_DATABASE_PASSWORD"] %>